#!/usr/bin/env bash
set -euxo pipefail

triplet="${1}"
dest=${2:-"/usr/local/${triplet}"}
mkdir -p "${dest}"

curl -fsSL "https://github.com/binarylandia/staticbourg/releases/download/2024-12-22_08-14-20/libxml2-2.12.9-static-${triplet}-2024-12-22_08-14-20.tar.gz" \
  | tar -C "${dest}" -xz

ls "${dest}/include/libxml/xmlreader.h"
ls "${dest}/lib/libxml2.a"
