#!/usr/bin/env bash
set -euxo pipefail

triplet="${1}"
dest=${2:-"/usr/local/${triplet}"}
mkdir -p "${dest}"

curl -fsSL "https://github.com/binarylandia/staticbourg/releases/download/2024-12-03_21-25-53/openssl-3.4.0-static-${triplet}-2024-12-03_21-25-53.tar.xz" \
  | pixz -dp "$(nproc)" \
  | tar -C "${dest}" -x

ls "${dest}/include/openssl/evp.h"
ls "${dest}/lib/libssl.a"
ls "${dest}/lib/libcrypto.a"
